# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import yurtube_pb2 as yurtube__pb2


class AdminIngestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushHealth = channel.unary_unary(
                '/ytadmin.AdminIngest/PushHealth',
                request_serializer=yurtube__pb2.PushHealthRequest.SerializeToString,
                response_deserializer=yurtube__pb2.PushAck.FromString,
                )
        self.PushEffConf = channel.unary_unary(
                '/ytadmin.AdminIngest/PushEffConf',
                request_serializer=yurtube__pb2.PushEffConfRequest.SerializeToString,
                response_deserializer=yurtube__pb2.PushAck.FromString,
                )


class AdminIngestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushEffConf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.PushHealth,
                    request_deserializer=yurtube__pb2.PushHealthRequest.FromString,
                    response_serializer=yurtube__pb2.PushAck.SerializeToString,
            ),
            'PushEffConf': grpc.unary_unary_rpc_method_handler(
                    servicer.PushEffConf,
                    request_deserializer=yurtube__pb2.PushEffConfRequest.FromString,
                    response_serializer=yurtube__pb2.PushAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytadmin.AdminIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminIngest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ytadmin.AdminIngest/PushHealth',
            yurtube__pb2.PushHealthRequest.SerializeToString,
            yurtube__pb2.PushAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PushEffConf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ytadmin.AdminIngest/PushEffConf',
            yurtube__pb2.PushEffConfRequest.SerializeToString,
            yurtube__pb2.PushAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
